lzc-sdk-version: 0.1
name: gokapi
package: cloud.lazycat.app.gokapi
version: 0.0.1
description: 
license: https://choosealicense.com/licenses/mit/
homepage: 
author: 
application:
  subdomain: gokapi
  routes:
    - /=http://gokapi.cloud.lazycat.app.gokapi.lzcapp:53842
  ingress:
    - protocol: tcp
      port: 53842
      service: gokapi
  background_task: true

services:
  gokapi:
    image: registry.lazycat.cloud/czyt/f0rc3/gokapi:8491074e73af38d8
    binds:
      - /lzcapp/var/gokapi/data:/app/data 
      - /lzcapp/var/gokapi/config:/app/config
    environment:
      - TZ=UTC
      - GOKAPI_DATA_DIR=/app/data
      - GOKAPI_CONFIG_DIR=/app/config
      - GOKAPI_PORT=53842
