lzc-sdk-version: 0.1
name: gokapi
package: cloud.lazycat.app.gokapi
version: 2.0.1
description: 
license: https://choosealicense.com/licenses/mit/
homepage: 
author: 
application:
  subdomain: gokapi
  routes:
    - /=http://gokapi:53842
  background_task: true

services:
  gokapi:
    image: docker.1ms.run/f0rc3/gokapi:v2.0.1
    binds:
      - /lzcapp/var/data:/app/data 
      - /lzcapp/var/config:/app/config
    environment:
      - TZ=UTC
      - GOKAPI_DATA_DIR=/app/data
      - GOKAPI_CONFIG_DIR=/app/config
      - GOKAPI_PORT=53842
